### ISSUE TITLE
TODO before making git repo public

### ISSUE THREAD

**Issue by theophanemayaud** [theophanemayaud/TriviaGo#5]
# Maps 
- [x] Remove old Maps Android SDK Keys for repo history (debug and release google_maps_api.xml)
- [x] Start using new Maps Android SDK Keys (in case they were made public...)

# Firebase
- [x] Remove old Firebase Api keys from repo history (google-services.json)
- [x] Start using new Firebase API Keys

# Sign key
- [x]  Create a shared signing key for deploy to play store, and for debug
- [x] Restrict debug maps api key to debug

# End
- [x] Either delete other branches, or make them specifically private
- [x] Make the repo public
